#!/usr/bin/env bash
set -euo pipefail

curl https://repo.anaconda.com/archive/Anaconda3-2021.11-Linux-x86_64.sh -o conda.sh

if [[ "$(sha256sum conda.sh)" != "fedf9e340039557f7b5e8a8a86affa9d299f5e9820144bd7b92ae9f7ee08ac60  conda.sh" ]]; then
  echo "Anaconda hash failed."
  exit 1
fi

chmod +x conda.sh

# -b = noninteractive
bash ./conda.sh -b

#
# AWS CLI
#

gpg --import data/aws-cli.pub

curl https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip     -o /tmp/aws.zip
curl https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip.sig -o /tmp/aws.zip.sig

gpg --verify /tmp/aws.zip.sig /tmp/aws.zip
rm -rf /tmp/aws.zip.sig

unzip -q /tmp/aws.zip -d /tmp
rm -f /tmp/aws.zip

if command -v aws &> /dev/null
then
  sudo ./aws/install --update
else
  sudo ./aws/install
fi

rm -rf /tmp/aws



# rm -rf aws
# popd > /dev/null

# # Perform all sudos as early as possible so the password is cached ^

# info "Installing home"

# mkdir -p "${HOME}/freyda"

# pushd home > /dev/null
# ln -sf "${PWD}/.bash_profile"       "${HOME}/.bash_profile"
# ln -sf "${PWD}/.gitconfig"          "${HOME}/.gitconfig"
# ln -sf "${PWD}/freyda/wev.user.yml" "${HOME}/freyda/wev.user.yml"
# popd > /dev/null

# if ! command -v git &> /dev/null
# then
#   info "Installing Git"
#   sudo apt install git -y
# fi

# if [ ! -d "${HOME}/.machine.secrets" ]
# then
#   # Intentionally use HTTP authentication since we don't have our SSH keys yet:

#   echo "⚠️  Visit https://github.com/settings/tokens/new to create a GitHub"
#   echo "⚠️  personal access token. The token can be revoked after"
#   echo "⚠️  machine.secrets has been cloned; your cloned SSH key will be used"
#   echo "⚠️  for subsequent pulls."
#   git clone https://github.com/cariad/machine.secrets.git "${HOME}/.machine.secrets"
# else
#   info "Updating machine.secrets"
#   pushd "${HOME}/.machine.secrets" > /dev/null
#   git pull git@github.com:cariad/machine.secrets.git
#   popd > /dev/null
# fi

# info "Restoring SSH keys"
# ln -sf "${HOME}/.machine.secrets/.ssh/config"         "${HOME}/.ssh/config"
# ln -sf "${HOME}/.machine.secrets/.ssh/id_ed25519"     "${HOME}/.ssh/id_ed25519"
# ln -sf "${HOME}/.machine.secrets/.ssh/id_ed25519.pub" "${HOME}/.ssh/id_ed25519.pub"

# if [ ! -d "${HOME}/.pyenv" ]
# then
#   info "Cloning pyenv"
#   git clone https://github.com/pyenv/pyenv.git "${HOME}/.pyenv"
# else
#   info "Pulling pyenv"
#   pushd "${HOME}/.pyenv" > /dev/null
#   git pull https://github.com/pyenv/pyenv.git
#   popd > /dev/null
# fi

# info "Compiling pyenv extension"
# pushd "${HOME}/.pyenv" > /dev/null
# src/configure
# make -C src
# popd > /dev/null

# source ~/.bash_profile

# info "Installing Python ${PYENV_VERSION}"
# pyenv install "${PYENV_VERSION}" --skip-existing

# info "Installing pipenv"
# pip install --upgrade pipenv

# info "Installing wev"
# pip install --upgrade wev
# pip install --upgrade wev-awscodeartifact

# info "Restoring GnuPG keys"
# gpg --import              ~/.machine.secrets/.gnupg/secret.txt
# gpg --import-ownertrust < ~/.machine.secrets/.gnupg/trust.txt

# info "Done!"

sudo apt autoremove -y

echo "Data Science machine successfully deployed!"
